[package]
name = "msvc-debug-test"
version = "0.1.0"
authors = ["tipeter <piotr.tihanyi@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
gio = "^0.5"

[target.'cfg(windows)'.build-dependencies]
vcpkg = "0.2.6"

[dependencies.gtk]
version = "^0.5"
features = ["v3_20"]
